export const HISTORY_KEY = "YT-history"
export const HOME_URL = "https://www.youtube.com"
export const SUBSCRIPTIONS_URL = "https://www.youtube.com/feed/subscriptions"
export const LIBRARY_URL = "https://www.youtube.com/feed/library"
export const HISTORY_URL = "https://www.youtube.com/feed/history"
export const WATCH_LATER_URL = "https://www.youtube.com/playlist?list=WL"
export const SHORTS_URL = "https://www.youtube.com/shorts"
